name: Build Spigot 1.21.4

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run BuildTools
        run: java -jar BuildTools.jar --rev 1.21.4

      - name: Archive generated jar
        uses: actions/upload-artifact@v4
        with:
          name: spigot-1.21.4
          path: ./spigot-1.21.4.jar
